# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticPoem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(verbose_name='Дата и время генерации')),
            ],
            options={
                'verbose_name_plural': 'Сгенерированные стихотворения',
                'verbose_name': 'Сгенерированное стихотворение',
            },
        ),
        migrations.CreateModel(
            name='GenerationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metre_schema', models.TextField(default='+-', verbose_name='Схема метра')),
                ('syllables_count', models.IntegerField(default=8, verbose_name='Количество слогов')),
                ('rhyme_schema', models.TextField(default='aabb', verbose_name='Схема рифмовки')),
            ],
            options={
                'verbose_name_plural': 'Наборы настроек генерации',
                'verbose_name': 'Набор настроек генерации',
            },
        ),
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='Слоговая разметка по ударениям')),
                ('author', models.CharField(max_length=50, verbose_name='Автор разметки')),
                ('additional', models.TextField(blank=True, verbose_name='Дополнительная ифнормация')),
            ],
            options={
                'verbose_name_plural': 'Разметки',
                'verbose_name': 'Разметка',
            },
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Нвзвание стихотворения')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('date_from', models.IntegerField(blank=True, null=True, verbose_name='Дата написания - первый год')),
                ('date_to', models.IntegerField(blank=True, null=True, verbose_name='Дата написания - второй год')),
            ],
            options={
                'verbose_name_plural': 'Стихотворения',
                'verbose_name': 'Стихотворение',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=50, verbose_name='Тема')),
            ],
            options={
                'verbose_name_plural': 'Темы',
                'verbose_name': 'Тема',
            },
        ),
        migrations.AddField(
            model_name='poem',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='poems', to='corpus.Theme', verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='markup',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='corpus.Poem'),
        ),
        migrations.AddField(
            model_name='automaticpoem',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='corpus.GenerationSettings', verbose_name='Настройки'),
        ),
    ]
