# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_auto_20170130_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsettings',
            name='line',
            field=models.TextField(blank=True, default='', verbose_name='Первая строчка'),
        ),
    ]
