# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-03 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_auto_20170414_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Markup',
            new_name='MarkupVersion',
        ),
    ]
