# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-03 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_auto_20170703_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='markupinstance',
            name='markup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='corpus.Markup'),
            preserve_default=False,
        ),
    ]
