# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_markupinstance_markup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markupinstance',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markup_instances', to='corpus.Poem'),
        ),
    ]
