# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_auto_20170704_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Markup',
            new_name='MarkupVersion',
        ),
        migrations.RemoveField(
            model_name='automaticpoem',
            name='settings',
        ),
        migrations.DeleteModel(
            name='AutomaticPoem',
        ),
        migrations.DeleteModel(
            name='GenerationSettings',
        ),
    ]
