# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0009_auto_20170820_1921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarkupInstance',
            new_name='Markup',
        ),
    ]
