# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0010_auto_20170820_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markupversion',
            options={'verbose_name': 'Версия разметки', 'verbose_name_plural': 'Версии разметки'},
        ),
        migrations.RenameField(
            model_name='markup',
            old_name='markup',
            new_name='markup_version',
        ),
        migrations.AlterField(
            model_name='markupversion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя версии разметки'),
        ),
    ]
