# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0011_auto_20170820_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markup',
            name='markup_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='corpus.MarkupVersion'),
        ),
        migrations.AlterField(
            model_name='markup',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='corpus.Poem'),
        ),
    ]
