# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_auto_20170827_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='markupversion',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Ручные разметки?'),
        ),
    ]
