# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0015_markup_is_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markup',
            old_name='text',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='theme',
            new_name='name',
        ),
    ]
