# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_corpus', '0002_auto_20161115_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='accent_tagging',
            new_name='accent_markup',
        ),
        migrations.RenameField(
            model_name='poem',
            old_name='syllable_tagging',
            new_name='syllable_markup',
        ),
    ]
