# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_corpus', '0003_auto_20161116_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='syllable_markup',
        ),
        migrations.AlterField(
            model_name='poem',
            name='accent_markup',
            field=models.TextField(blank=True, default='', verbose_name='Слоговая разметка по ударениям'),
        ),
    ]
